### ISSUE TITLE
[Help] in8sn is deleted when restarting android

### ISSUE THREAD

**Issue by giovEra** [luk1337/ih8sn#10]
Hi,
I have compiled and installed in8sn on my Xiaomi Redmi Note 9 Pro (miatoll), and it works perfectly, (I tried to run it from adb).

_The problem is:_
every time I restart android, in8sn disappears from ``/system/bin``, so it won't start automatically because the binary doesn't exist anymore.
How do I get in8sn is not deleted from ``/system/bin`` after rebooting the phone?

ROM: [(Official) LineageOS 18.1](https://wiki.lineageos.org/devices/miatoll/)

Note:
- for reboot I mean hold down the power button of the phone and in the menu that appears I press "reboot"
- I have installed ih8sn with the provided script

Thanks for your attention, and I hope for an answer :)

**Comment by JoergPalmer** [comment]
> Hi, I have compiled and installed in8sn on my Xiaomi Redmi Note 9 Pro (miatoll), and it works perfectly, (I tried to run it from adb).

I'm running LineageOS 18.1 on a Pocophone F1 (code name beryllium). I would like to compile and build, but so far to no avail :-( I have downloaded the Android NDK android-ndk-r23b, and I have adjusted the CXX variable in build.sh to "aarch64-linux-android30-clang++". CMake, gcc and build-essentials are installed on my machine. But all I'm getting from running build.sh is 

`clang-12: error: no input files`

Could someone point me in the right direction, please?

To your problem, did you double-check for the existence of 60-ih8sn.sh in /system/addon.d/? From what I learned, this file would/should be executed on boot.

**Comment by luk1337** [comment]
@giovEra no clue, but you can try replacing adb remount with `adb shell mount -o rw,remount /` in push.sh
@JoergPalmer Look at https://github.com/luk1337/ih8sn/blob/master/.github/workflows/build.yml#L11-L14 + https://github.com/luk1337/ih8sn/blob/master/.github/workflows/build.yml#L23-L26

**Comment by giovEra** [comment]
Thanks for the reply.

ih8sn keeps disappearing...and I don't understand why.

With both commands (``adb remount`` and ``adb shell mount -o rw,remount /``) the partition "/" is re-mounted in RW.
in fact after executing one of the two commands for remounting, the output of ``adb shell mount | grep "/ "`` is:
```
/dev/block/dm-0 on / type ext4 (rw,seclabel,relatime,discard,errors=remount-ro)
```
ih8sn (binary file) is the only file that does not survive after reboot, the other three files (.rc .sh .config) survive after reboot.

@luk1337 do you have any advice? What could I check to see where the problem is?

---

I seriously don't understand why 😢 , it's a read-write mounted partition that I write a file to, why does the file disappear? I just turned the phone off and on again.
I feel stupid 😆

**Comment by tzagim** [comment]
> Hi, I have compiled and installed in8sn on my Xiaomi Redmi Note 9 Pro (miatoll), and it works perfectly, (I tried to run it from adb).
> 
> _The problem is:_ every time I restart android, in8sn disappears from `/system/bin`, so it won't start automatically because the binary doesn't exist anymore. How do I get in8sn is not deleted from `/system/bin` after rebooting the phone?
> 
> ROM: [(Official) LineageOS 18.1](https://wiki.lineageos.org/devices/miatoll/)
> 
> Note:
> 
>     * for reboot I mean hold down the power button of the phone and in the menu that appears I press "reboot"
> 
>     * I have installed ih8sn with the provided script
> 
> 
> Thanks for your attention, and I hope for an answer :)

The same thing happens to me

**Comment by luk1337** [comment]
@tzagim on what device?

**Comment by tzagim** [comment]
> @tzagim on what device?

surya (PCOO X3 NFC)

**Comment by luk1337** [comment]
Do you have any mods? Can you post full `adb shell mount` output?

**Comment by tzagim** [comment]
> Do you have any mods? Can you post full `adb shell mount` output?

I think it's happening because of magic

**Comment by luk1337** [comment]
Ehh, I'll think of some way to workaround that, maybe.

**Comment by luk1337** [comment]
Yeah, magisk mounts whole /system/bin on tmpfs, that'd explain it.

**Comment by tzagim** [comment]
I was thinking of trying to run it as a zip in recovery to overcome the problem, but I have not been able to do it yet.
I'm unable to mount the system.
I do not know if it is related or I just don't succeed.

**Comment by luk1337** [comment]
Edit push.sh or push.ps1 and put `adb shell "mount | grep -q ^tmpfs\ on\ /system && umount -fl /system/etc /system/bin 2>/dev/null"` before `adb wait-for-device remount`. Let me know if that does anything.

**Comment by tzagim** [comment]
> Edit push.sh or push.ps1 and put `adb wait-for-device shell "mount | grep -q ^tmpfs\ on\ /system && umount -fl /system/{bin,etc} 2>/dev/null"` before `adb wait-for-device remount`. Let me know if that does anything.

Same thing, deleted on reboot.
By the way, it seems to me is better to change `adb` in push.ps1 to `.\adb`

**Comment by luk1337** [comment]
Try:
```
adb wait-for-device root
adb wait-for-device shell "mount | grep -q ^tmpfs\ on\ /system && umount -fl /system/{bin,etc} 2>/dev/null"
adb wait-for-device shell "mount -o rw,remount / 2>/dev/null || mount -o rw,remount /system 2>/dev/null || remount"
adb wait-for-device push 60-ih8sn.sh /system/addon.d/
adb wait-for-device push ih8sn /system/bin/
adb wait-for-device push ih8sn.rc /system/etc/init/
```

Also, it's not better to use `.\adb`, you should setup your environment variables to have adb accessible system-wide instead.

**Comment by tzagim** [comment]
> adb wait-for-device root
> adb wait-for-device shell "mount | grep -q ^tmpfs\ on\ /system && umount -fl /system/{bin,etc} 2>/dev/null"
> adb wait-for-device shell "mount -o rw,remount / 2>/dev/null || mount -o rw,remount /system 2>/dev/null || remount"
> adb wait-for-device push 60-ih8sn.sh /system/addon.d/
> adb wait-for-device push ih8sn /system/bin/
> adb wait-for-device push ih8sn.rc /system/etc/init/

it worked! The file was not deleted!!

**Comment by luk1337** [comment]
Ok, now adb remount use is opt-in. See: https://github.com/luk1337/ih8sn/commit/ab1b8ee87e353505b27bbad4ca9354761430a1f3 for more info.

**Comment by giovEra** [comment]
I confirm that it now works on mine as well.
Thank you 👍
