### ISSUE TITLE
[Help] Building for beryllium

### ISSUE THREAD

**Issue by JoergPalmer** [luk1337/ih8sn#11]
Didn't mean to pollute the #10, sorry

I'm running LineageOS 18.1 on a Pocophone F1 (code name beryllium). I would like to compile and build this project, but so far to no avail :-( My goal is to get rid of root, since I don't really need it. Magisk is currently installed solely for passing the safety net check.

I have downloaded the Android NDK android-ndk-r23b (current version), and I have adjusted the CXX variable in build.sh to "aarch64-linux-android30-clang++", since I figured that version is needed to match my LOS build which is representing Android 11. CMake (v3.22.2), gcc (v11.2.1) and build-essentials are installed on my machine (openSuSE Tumbleweed). But all I'm getting from running build.sh with this command:

`ANDROID_NDK_HOME=../android-ndk-r23b CXX=aarch64-linux-android30-clang++ ./build.sh`
 is
`clang-13.0: error: no input files`

Could someone point me in the right direction, please? I must miss some setting/adjustment, but I can't figure what that could be.

On a lighter note, I have created a configuration "ih8sn.conf.beryllium", just in case someone is interested. From what I figured it will be installed using "push.sh" ... when I get there eventually.

**Comment by luk1337** [comment]
My suggestion from https://github.com/luk1337/ih8sn/issues/10#issuecomment-1026870241 still stands.

**Comment by JoergPalmer** [comment]
> My suggestion from [#10 (comment)](https://github.com/luk1337/ih8sn/issues/10#issuecomment-1026870241) still stands.

Sorry for my lack of knowledge ... I have used the command as mentioned there. The difference is only that I'm using version r23b of Android NDK, and I'm using android30 since I figured it should match the target Android version. Do you recommend using the older version of NDK (21) and android29 as target?

**Comment by luk1337** [comment]
I suggest copy pasting every command as is.

**Comment by luk1337** [comment]
Also updated Ci to r23b and it compiles just fine.

**Comment by JoergPalmer** [comment]
OK .. I downloaded r21 (r21e to be exact), and it builds with no problem. For me, it fails with r23b .. still no clue why that is. The environment itself seems to be OK since it builds with r21. On a lighter note, using r21 I can build both, android29 and android30 versions, if that is of any importance.

Either way, going to install this on my beryllium to check if it helps to get rid of magisk. Thanks for your help!

**Comment by luk1337** [comment]
Unless you modified build.sh then r23b should also compile. But w/e, also target version shouldn't matter since ih8sn is statically linked anyway.
