### ISSUE TITLE
Are missing properties a problem?

### ISSUE THREAD

**Issue by x10an14** [luk1337/ih8sn#12]
Hi!

I used `push.sh`, and I confirmed that (on next reboot) flags like `ro.boot.verifiedbootstate` were set as described in `main.cpp`.

Some flags, however, are not present/listed all when invoking `getprop` (e.g. `ro.boot.flash.locked`).

So my main question is if a missing property can be a sign of something having gone wrong?
I'm unable to pass SafetyNet at least.

Follow-up question, is there some debug log I can read? I haven't read the source code yet, but since I saw nothing that reminded me of it in `main.cpp`, I thought I'd ask before "giving up" that hope.

**Comment by luk1337** [comment]
No, just look at getprop and see if everything you wanted to be set is set. It's up to you to figure out what props to override in config to make snet happy, also be aware that this tool isn't trying to downgrade your device from hw attestation to basic attestation.
