### ISSUE TITLE
No network when ih8sn is installed on davinci

### ISSUE THREAD

**Issue by Spiffyk** [luk1337/ih8sn#19]
When I install `ih8sn` on my `davinci` with LineageOS 19 UNOFFICIAL, all network (i.e. WiFi, mobile data, Bluetooth etc.) stops working. It seems that the system loses a way to access the devices, because the settings for these hang in strange ways.

Network starts working again when I remove `/bin/ih8sn` and `/etc/init/ih8sn.rc`. Is there some known way to fix this or a hint as to how to debug this problem?

**Comment by luk1337** [comment]
Does that happen with an empty config file?

**Comment by Spiffyk** [comment]
I've tried multiple configurations, including with everything commented out and configuring it with values from the latest stock ROM. I should note that the latest ROM is Android 11. Do mismatching Android versions of the fingerprint and the actual ROM cause problems? I.e. should I wait until/if Xiaomi releases an official Android 12 stock ROM for the device (or downgrade to LineageOS 18)?

**Comment by luk1337** [comment]
If you're able to compile, then try to find out which property override breaks it.

**Comment by Spiffyk** [comment]
And I should try commenting out the ones at the bottom of `main.cpp`, i.e. on lines 130-135, one by one, correct?

**Comment by luk1337** [comment]
Yeah, these are the only prop overrides that aren't optional.

**Comment by Spiffyk** [comment]
Network works with `ro.boot.verifiedbootstate` commented out. SafetyNet verification fails, though.

**Comment by luk1337** [comment]
hmm, that's unexpected...

**Comment by luk1337** [comment]
Try to wrap last 5 overrides with `is_boot_completed_stage`.

**Comment by Spiffyk** [comment]
That fixes it and SafetyNet passes!

**Comment by luk1337** [comment]
Can you open PR? ^.^

**Comment by Spiffyk** [comment]
Will do! Thanks for the help.
