### ISSUE TITLE
Does it work with Android 13?

### ISSUE THREAD

**Issue by tinsukE** [luk1337/ih8sn#42]
I had made it work on my OnePlus 6 running LineageOS 19 (Android 12), surviving OTAs, the whole thing.

After upgrading to LineageOS 20 (Android 13), it stopped working (Google Wallet says phone doesn't meet security requirements, Netflix isn't available via Play Store; things that used to work) and I tried to do the whole setup again in the hopes that the Android version upgrade had borked it, but without success.

Should `ih8sn` even work with Android 13? (so I don't keep trying aimlessly in case it doesn't).

**Comment by thecrazyblack** [comment]
Maybe this is google issue or new implement method by google to check safetynet

**Comment by tinsukE** [comment]
Indeed, I've seen some more reports floating around that suggest this might be the case.

Closing this issue.
